---
driver:
  name: vagrant
  customize:
    memory: 4096

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-18.04
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[orientdb::default]
    attributes:
      orientdb:
        version: '3.0.8'

# default['orientdb']['hazelcast']['network']['join']['aws']['access-key'] = 'my-access-key'
# default['orientdb']['hazelcast']['network']['join']['aws']['secret-key'] = 'my-secret-key'
# default['orientdb']['hazelcast']['network']['join']['aws']['region'] = 'us-west-1'
# default['orientdb']['hazelcast']['network']['join']['aws']['security-group-name'] = 'hazelcast-sg'
# default['orientdb']['hazelcast']['network']['join']['aws']['tag-key'] = 'type'
# default['orientdb']['hazelcast']['network']['join']['aws']['tag-value'] = 'hz-nodes'
#
#
# default['orientdb']['node_search_criteria'] = "orientdb_hazelcast_group_name:#{node['orientdb']['hazelcast']['group']['name']} AND orientdb_hazelcast_group_password:#{node['orientdb']['hazelcast']['group']['password']}"
